In [1]:
import pandas as pd
import numpy as np
NaN = np.nan
from pyobistools.validation.check_scientificname_and_ids import check_scientificname_and_ids
import plotly.express as px
pd.set_option('max_colwidth', None)
import nest_asyncio
nest_asyncio.apply()

### Info about this notebook series

This series of notebook is meant to serve as an educational tool to learn how to use the PyObis biodiversity data validation package: + https://github.com/cioos-siooc/pyobistools

Darwin Core documentation: 
+ https://dwc.tdwg.org/

Darwin Core file types required fields: 
+ https://ioos.github.io/bio_mobilization_workshop/01-introduction/index.html
+ https://ioos.github.io/bio_mobilization_workshop/04-create-schema/index.html

### Notebook to test Pyobis' function 'check_scientifiname_and_ids'

##### Function 'check_scientifiname_and_ids' description
This function is used to evaluate the validity of scientific names, scientific name Ids and taxon ranks with Worms and Itis databases

##### Function 'check_scientifiname_and_ids' arguments
+ data: Dataframe of the data to evaluate
+ value: Type of analysis to run for each row in the dataset 
    + 'names': Analyzes scientific names validity with Worms and Itis (Itis optional)
    + 'names_ids': Above plus analyzes scientific name Ids
    + 'names_taxons_ids': Above plus analyzes taxon rank
+ itis_usage (default =  False): Option to validate data also with Itis if Worms service does not provide a positive answer for a given scientific name

Load different types of DWC files:

In [2]:
occurrence_core =      pd.read_csv('https://catalogue.ogsl.ca/data/ncc/ca-cioos_b52bb8be-d225-442c-94ab-6f107a64b8a6/saint_john_river_saltmarshes_species-occurrence_2021.csv')
occurrence_extension = pd.read_csv('https://catalogue.ogsl.ca/data/ismer/ca-cioos_0edfc94f-06d0-4823-84ef-df91e6c11fe6/ismer_occurrence_endofaune_cote-nord_2009.csv')
occurrence_extension.head(3)

,eventID,occurrenceID,scientificName,aphiaID,scientificNameID,taxonRank,occurrenceStatus,organismQuantityType,organismQuantity,basisofRecord
0,0003_Infauna_CoteNord_CamilleRobineau_BE10C1,0003_Infauna_CoteNord_CamilleRobineau_BE10C1_1,Mesodesma arctatum,156805.0,urn:lsid:marinespecies.org:taxname:156805,species,present,Individual count,2,HumanObservation
1,0003_Infauna_CoteNord_CamilleRobineau_BE10C1,0003_Infauna_CoteNord_CamilleRobineau_BE10C1_2,Nephtys ciliata,130356.0,urn:lsid:marinespecies.org:taxname:130356,species,present,Individual count,1,HumanObservation
2,0003_Infauna_CoteNord_CamilleRobineau_BE10C2,0003_Infauna_CoteNord_CamilleRobineau_BE10C2_3,Leucon nasicoides,148682.0,urn:lsid:marinespecies.org:taxname:148682,species,present,Individual count,2,HumanObservation

Try the check_scientificname_and_ids function:

In [7]:
check_scientificname_and_ids(occurrence_core, 'names').head()

3 : 200: Worms Asteraceae
14 : 204: Worms Acorus americanus
19 : 204: Worms Chelone glabra
41 : 200: Worms Glyceria
46 : 204: Worms Epalpus signifer
59 : 204: Worms Hylaeus
92 : 204: Worms Harmonia axyridis
106 : 204: Worms Calystegia sepium
86 : 204: Worms Lycopus uniflorus
80 : 204: Worms Dasiphora fruticosa
88 : 200: Worms Elodea canadensis
90 : 200: Worms Liliopsida
119 : 204: Worms Fraxinus pennsylvanica
69 : 204: Worms Pastinaca sativa
113 : 200: Worms Polistes fuscatus
91 : 200: Worms Doellingeria umbellata
121 : 200: Worms Galium mollugo
85 : 200: Worms Spergularia marina
1 : 200: Worms Lonicera
103 : 204: Worms Echinocystis lobata
98 : 200: Worms Elymus virginicus
5 : 200: Worms Eutrochium maculatum
83 : 200: Worms Typha
4 : 200: Worms Senecio
109 : 204: Worms Quercus rubra
89 : 200: Worms Erechtites hieraciifolius
0 : 200: Worms Carex
97 : 200: Worms Salix
82 : 204: Worms Prunella vulgaris
94 : 200: Worms Myriophyllum spicatum
66 : 204: Worms Alnus alnobetula
102 : 200: Worms Eleocharis palustris
78 : 200: Worms Sagittaria latifolia
100 : 204: Worms Stachys palustris
20 : 200: Worms Jacobaea vulgaris
87 : 200: Worms Eleocharis uniglumis
81 : 200: Worms Vicia cracca
95 : 204: Worms Impatiens capensis
23 : 200: Worms Poaceae
27 : 200: Worms Galium
8 : 200: Worms Cirsium arvense
47 : 200: Worms Stuckenia pectinata
22 : 200: Worms Rosaceae
108 : 200: Worms Cyperaceae
84 : 200: Worms Senecio viscosus
120 : 200: Worms Centaurea nigra
93 : 200: Worms Bryophyta
105 : 204: Worms Arisaema triphyllum
74 : 200: Worms Zizania
2 : 204: Worms Lysimachia maritima
33 : 200: Worms Leucanthemum vulgare
101 : 200: Worms Cichorieae
6 : 200: Worms Rumex
30 : 204: Worms Cornus rugosa
48 : 200: Worms Ranunculus repens
45 : 204: Worms Lysimachia terrestris
26 : 204: Worms Scutellaria galericulata
43 : 200: Worms Sonchus arvensis
38 : 200: Worms Persicaria
39 : 204: Worms Iris versicolor
12 : 200: Worms Osmunda spectabilis
36 : 204: Worms Persicaria maculosa
35 : 200: Worms Tanacetum
7 : 204: Worms Argentina anserina
18 : 204: Worms Athyrium angustum
31 : 200: Worms Castor canadensis
111 : 200: Worms Chenopodium album
16 : 200: Worms Tussilago farfara
24 : 200: Worms Plantago
61 : 204: Worms Reynoutria japonica
34 : 200: Worms Ulva intestinalis
42 : 200: Worms Cichorium intybus
9 : 200: Worms Agrostis gigantea
44 : 204: Worms Alisma triviale
53 : 204: Worms Euphorbia maculata
138 : 200: Worms Larus argentatus
56 : 200: Worms Calidris minutilla
15 : 204: Worms Phalaris arundinacea
115 : 204: Worms Frangula alnus
29 : 200: Worms Osmunda claytoniana
99 : 204: Worms Apocynum cannabinum
126 : 204: Worms Betula papyrifera
25 : 204: Worms Fraxinus
58 : 204: Worms Stellaria graminea
107 : 200: Worms Typha latifolia
21 : 204: Worms Berberis thunbergii
71 : 200: Worms Centaurea jacea
112 : 204: Worms Scutellaria lateriflora
136 : 204: Worms Mentha canadensis
68 : 204: Worms Hypericum mutilum
124 : 204: Worms Rhagonycha fulva
104 : 200: Worms Symphyotrichum
67 : 200: Worms Schoenoplectus tabernaemontani
32 : 204: Worms Schoenoplectus pungens
64 : 200: Worms Rubus
37 : 204: Worms Alnus incana
116 : 204: Worms Matteuccia struthiopteris
125 : 200: Worms Xanthium strumarium
54 : 204: Worms Hylotelephium telephium
130 : 204: Worms Solanum dulcamara
55 : 200: Worms Megaceryle alcyon
28 : 204: Worms Spiraea alba
131 : 200: Worms Cirsium
117 : 204: Worms Carex pallescens
17 : 204: Worms Oxybasis rubra
122 : 204: Worms Viburnum opulus
13 : 200: Worms Ruppia maritima
40 : 204: Worms Amphicarpaea bracteata
57 : 204: Worms Thalictrum pubescens
10 : 204: Worms Myrica gale
52 : 200: Worms Plantago major
49 : 204: Worms Sium suave
11 : 204: Worms Convallaria majalis
114 : 204: Worms Ilex verticillata
50 : 204: Worms Hypericum perforatum
63 : 200: Worms Euthamia
51 : 204: Worms Halerpestes cymbalaria
60 : 200: Worms Nuphar
132 : 200: Worms Scirpus
128 : 200: Worms Vicia
70 : 204: Worms Persicaria sagittata
139 : 204: Worms Scirpus microcarpus
134 : 200: Worms Raphanus raphanistrum
129 : 200: Worms Bidens
76 : 200: Worms Juncus
72 : 204: Worms Persicaria amphibia
141 : 204: Worms Thelypteris palustris
144 : 200: Worms Juncus gerardii
118 : 200: Worms Onoclea sensibilis
133 : 200: Worms Oenothera
110 : 204: Worms Sporobolus michauxianus
62 : 204: Worms Iris hookeri
77 : 200: Worms Anthoxanthum odoratum
79 : 204: Worms Linaria vulgaris
75 : 204: Worms Acer rubrum
65 : 200: Worms Tracheophyta
73 : 204: Worms Cornus sericea
135 : 200: Worms Tanacetum vulgare
123 : 204: Worms Crataegus
127 : 204: Worms Lysimachia ciliata
137 : 200: Worms Lythrum salicaria
140 : 200: Worms Thuja occidentalis
142 : 200: Worms Rosa
96 : 204: Worms Sorbus
143 : 200: Worms Schoenoplectus

              Dataset Values  Validation Database values         \
              scientificname Exact_Match         TaxonID Status
0       Phalaris arundinacea      Non/no
110           Cornus sericea      Non/no
63   Hylotelephium telephium      Non/no
112            Cornus rugosa      Non/no
60      Thalictrum pubescens      Non/no


    Unacceptreason Taxon_Rank Valid_TaxonID Valid_Name LSID
0
110
63
112
60

In [8]:
check_scientificname_and_ids(occurrence_extension, 'names').head()

2 : 200: Worms Macoma balthica
1 : 200: Worms Leucon nasicoides
8 : 200: Worms Microspio
10 : 200: Worms Nematoda
11 : 200: Worms Gammarus oceanicus
13 : 200: Worms Idotea balthica
18 : 200: Worms Nephtys ciliata
4 : 200: Worms Oligochaeta
5 : 200: Worms Eteone longa
17 : 200: Worms Hydrobia minuta
12 : 200: Worms Oediceros borealis
14 : 200: Worms Mya arenaria
7 : 200: Worms Littorina obtusata
3 : 200: Worms Nereis diversicolor
6 : 200: Worms Mytilus edulis
16 : 200: Worms Mesodesma arctatum
9 : 200: Worms Littorina saxatilis
15 : 200: Worms Psammonyx nobilis

         Dataset Values  Validation Database values                            \
         scientificname Exact_Match         TaxonID                    Status
2     Leucon nasicoides      Non/no          148682  alternate representation
4     Psammonyx nobilis      Non/no          158140                unaccepted
8   Nereis diversicolor      Non/no          340537                   deleted
11      Hydrobia minuta      Non/no          152020                unaccepted
0    Mesodesma arctatum     Oui/Yes          156805                  accepted

                                                       \
              Unacceptreason Taxon_Rank Valid_TaxonID
2                       None    Species        110619
4   superseded recombination    Species       1255501
8       AphiaID resurrection       None        152302
11          preoccupied name    Species        574096
0                       None    Species        156805


                    Valid_Name                                       LSID
2   Leucon (Leucon) nasicoides  urn:lsid:marinespecies.org:taxname:148682
4            Wecomedon nobilis  urn:lsid:marinespecies.org:taxname:158140
8         Hediste diversicolor  urn:lsid:marinespecies.org:taxname:340537
11            Ecrobia truncata  urn:lsid:marinespecies.org:taxname:152020
0           Mesodesma arctatum  urn:lsid:marinespecies.org:taxname:156805

In [9]:
table1, table2 = check_scientificname_and_ids(occurrence_core, 'names_ids')
table1.head(3)

3 : 200: Worms Asteraceae
2 : 204: Worms Lysimachia maritima
1 : 200: Worms Lonicera
5 : 200: Worms Eutrochium maculatum
7 : 204: Worms Argentina anserina
10 : 204: Worms Myrica gale
0 : 200: Worms Carex
4 : 200: Worms Senecio
6 : 200: Worms Rumex
17 : 204: Worms Oxybasis rubra
14 : 204: Worms Acorus americanus
9 : 200: Worms Agrostis gigantea
13 : 200: Worms Ruppia maritima
12 : 200: Worms Osmunda spectabilis
19 : 204: Worms Chelone glabra
8 : 200: Worms Cirsium arvense
11 : 204: Worms Convallaria majalis
21 : 204: Worms Berberis thunbergii
15 : 204: Worms Phalaris arundinacea
16 : 200: Worms Tussilago farfara
18 : 204: Worms Athyrium angustum
23 : 200: Worms Poaceae
36 : 204: Worms Persicaria maculosa
26 : 204: Worms Scutellaria galericulata
25 : 204: Worms Fraxinus
32 : 204: Worms Schoenoplectus pungens
37 : 204: Worms Alnus incana
40 : 204: Worms Amphicarpaea bracteata
51 : 204: Worms Halerpestes cymbalaria
29 : 200: Worms Osmunda claytoniana
22 : 200: Worms Rosaceae
28 : 204: Worms Spiraea alba
30 : 204: Worms Cornus rugosa
66 : 204: Worms Alnus alnobetula
72 : 204: Worms Persicaria amphibia
45 : 204: Worms Lysimachia terrestris
46 : 204: Worms Epalpus signifer
61 : 204: Worms Reynoutria japonica
27 : 200: Worms Galium
53 : 204: Worms Euphorbia maculata
24 : 200: Worms Plantago
38 : 200: Worms Persicaria
39 : 204: Worms Iris versicolor
50 : 204: Worms Hypericum perforatum
20 : 200: Worms Jacobaea vulgaris
44 : 204: Worms Alisma triviale
62 : 204: Worms Iris hookeri
57 : 204: Worms Thalictrum pubescens
41 : 200: Worms Glyceria
52 : 200: Worms Plantago major
49 : 204: Worms Sium suave
74 : 200: Worms Zizania
77 : 200: Worms Anthoxanthum odoratum
82 : 204: Worms Prunella vulgaris
42 : 200: Worms Cichorium intybus
47 : 200: Worms Stuckenia pectinata
34 : 200: Worms Ulva intestinalis
54 : 204: Worms Hylotelephium telephium
31 : 200: Worms Castor canadensis
56 : 200: Worms Calidris minutilla
70 : 204: Worms Persicaria sagittata
58 : 204: Worms Stellaria graminea
43 : 200: Worms Sonchus arvensis
73 : 204: Worms Cornus sericea
65 : 200: Worms Tracheophyta
68 : 204: Worms Hypericum mutilum
59 : 204: Worms Hylaeus
96 : 204: Worms Sorbus
48 : 200: Worms Ranunculus repens
88 : 200: Worms Elodea canadensis
71 : 200: Worms Centaurea jacea
91 : 200: Worms Doellingeria umbellata
131 : 200: Worms Cirsium
75 : 204: Worms Acer rubrum
55 : 200: Worms Megaceryle alcyon
110 : 204: Worms Sporobolus michauxianus
35 : 200: Worms Tanacetum
102 : 200: Worms Eleocharis palustris
87 : 200: Worms Eleocharis uniglumis
83 : 200: Worms Typha
89 : 200: Worms Erechtites hieraciifolius
98 : 200: Worms Elymus virginicus
122 : 204: Worms Viburnum opulus
117 : 204: Worms Carex pallescens
69 : 204: Worms Pastinaca sativa
100 : 204: Worms Stachys palustris
78 : 200: Worms Sagittaria latifolia
80 : 204: Worms Dasiphora fruticosa
79 : 204: Worms Linaria vulgaris
118 : 200: Worms Onoclea sensibilis
76 : 200: Worms Juncus
67 : 200: Worms Schoenoplectus tabernaemontani
103 : 204: Worms Echinocystis lobata
92 : 204: Worms Harmonia axyridis
105 : 204: Worms Arisaema triphyllum
107 : 200: Worms Typha latifolia
64 : 200: Worms Rubus
33 : 200: Worms Leucanthemum vulgare
112 : 204: Worms Scutellaria lateriflora
99 : 204: Worms Apocynum cannabinum
93 : 200: Worms Bryophyta
94 : 200: Worms Myriophyllum spicatum
86 : 204: Worms Lycopus uniflorus
109 : 204: Worms Quercus rubra
60 : 200: Worms Nuphar
90 : 200: Worms Liliopsida
95 : 204: Worms Impatiens capensis
81 : 200: Worms Vicia cracca
114 : 204: Worms Ilex verticillata
85 : 200: Worms Spergularia marina
104 : 200: Worms Symphyotrichum
121 : 200: Worms Galium mollugo
111 : 200: Worms Chenopodium album
84 : 200: Worms Senecio viscosus
128 : 200: Worms Vicia
108 : 200: Worms Cyperaceae
113 : 200: Worms Polistes fuscatus
101 : 200: Worms Cichorieae
97 : 200: Worms Salix
63 : 200: Worms Euthamia

          Dataset Values  Validation Database values                        \
          scientificname Exact_Match         TaxonID Status Unacceptreason
0   Phalaris arundinacea      Non/no
89   Apocynum cannabinum      Non/no
85        Frangula alnus      Non/no


   Taxon_Rank Valid_TaxonID Valid_Name LSID
0
89
85

In [10]:
table2.head(3)

                                  Ref. ID                Validation  \
                             OccurrenceID ScientificName_Validation
0  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-001                    Non/no
1  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-002                    Non/no
2  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-003                    Non/no

                                        Dataset Values  \
  scientificNameID_Validation           ScientificName
0                      Non/No     Phalaris arundinacea
1                      Non/No  Sporobolus michauxianus
2                      Non/No   Schoenoplectus pungens

                                      Database values
                     ScientificNameID      Valid_Name LSID
0    urn:lsid:itis.gov:itis_tsn:41335
1  urn:lsid:ipni.org:names:77145291-1
2   urn:lsid:itis.gov:itis_tsn:508146

In [11]:
table3, table4 = check_scientificname_and_ids(occurrence_core, 'names_taxons_ids')
table3.head(3)

6 : 200: Worms Rumex
8 : 200: Worms Cirsium arvense
2 : 204: Worms Lysimachia maritima
17 : 204: Worms Oxybasis rubra
18 : 204: Worms Athyrium angustum
15 : 204: Worms Phalaris arundinacea
19 : 204: Worms Chelone glabra
3 : 200: Worms Asteraceae
44 : 204: Worms Alisma triviale
16 : 200: Worms Tussilago farfara
37 : 204: Worms Alnus incana
7 : 204: Worms Argentina anserina
14 : 204: Worms Acorus americanus
4 : 200: Worms Senecio
5 : 200: Worms Eutrochium maculatum
1 : 200: Worms Lonicera
40 : 204: Worms Amphicarpaea bracteata
0 : 200: Worms Carex
23 : 200: Worms Poaceae
29 : 200: Worms Osmunda claytoniana
22 : 200: Worms Rosaceae
9 : 200: Worms Agrostis gigantea
11 : 204: Worms Convallaria majalis
13 : 200: Worms Ruppia maritima
28 : 204: Worms Spiraea alba
10 : 204: Worms Myrica gale
20 : 200: Worms Jacobaea vulgaris
12 : 200: Worms Osmunda spectabilis
27 : 200: Worms Galium
47 : 200: Worms Stuckenia pectinata
52 : 200: Worms Plantago major
32 : 204: Worms Schoenoplectus pungens
26 : 204: Worms Scutellaria galericulata
21 : 204: Worms Berberis thunbergii
45 : 204: Worms Lysimachia terrestris
30 : 204: Worms Cornus rugosa
48 : 200: Worms Ranunculus repens
33 : 200: Worms Leucanthemum vulgare
41 : 200: Worms Glyceria
50 : 204: Worms Hypericum perforatum
31 : 200: Worms Castor canadensis
51 : 204: Worms Halerpestes cymbalaria
25 : 204: Worms Fraxinus
46 : 204: Worms Epalpus signifer
24 : 200: Worms Plantago
38 : 200: Worms Persicaria
43 : 200: Worms Sonchus arvensis
42 : 200: Worms Cichorium intybus
34 : 200: Worms Ulva intestinalis
35 : 200: Worms Tanacetum
76 : 200: Worms Juncus
82 : 204: Worms Prunella vulgaris
92 : 204: Worms Harmonia axyridis
91 : 200: Worms Doellingeria umbellata
100 : 204: Worms Stachys palustris
80 : 204: Worms Dasiphora fruticosa
49 : 204: Worms Sium suave
60 : 200: Worms Nuphar
36 : 204: Worms Persicaria maculosa
88 : 200: Worms Elodea canadensis
83 : 200: Worms Typha
84 : 200: Worms Senecio viscosus
75 : 204: Worms Acer rubrum
73 : 204: Worms Cornus sericea
68 : 204: Worms Hypericum mutilum
87 : 200: Worms Eleocharis uniglumis
95 : 204: Worms Impatiens capensis
70 : 204: Worms Persicaria sagittata
78 : 200: Worms Sagittaria latifolia
86 : 204: Worms Lycopus uniflorus
79 : 204: Worms Linaria vulgaris
72 : 204: Worms Persicaria amphibia
90 : 200: Worms Liliopsida
85 : 200: Worms Spergularia marina
71 : 200: Worms Centaurea jacea
103 : 204: Worms Echinocystis lobata
121 : 200: Worms Galium mollugo
61 : 204: Worms Reynoutria japonica
58 : 204: Worms Stellaria graminea
122 : 204: Worms Viburnum opulus
67 : 200: Worms Schoenoplectus tabernaemontani
53 : 204: Worms Euphorbia maculata
96 : 204: Worms Sorbus
109 : 204: Worms Quercus rubra
59 : 204: Worms Hylaeus
111 : 200: Worms Chenopodium album
57 : 204: Worms Thalictrum pubescens
127 : 204: Worms Lysimachia ciliata
56 : 200: Worms Calidris minutilla
55 : 200: Worms Megaceryle alcyon
54 : 204: Worms Hylotelephium telephium
62 : 204: Worms Iris hookeri
66 : 204: Worms Alnus alnobetula
64 : 200: Worms Rubus
65 : 200: Worms Tracheophyta
69 : 204: Worms Pastinaca sativa
39 : 204: Worms Iris versicolor
93 : 200: Worms Bryophyta
74 : 200: Worms Zizania
104 : 200: Worms Symphyotrichum
97 : 200: Worms Salix
99 : 204: Worms Apocynum cannabinum
106 : 204: Worms Calystegia sepium
77 : 200: Worms Anthoxanthum odoratum
110 : 204: Worms Sporobolus michauxianus
94 : 200: Worms Myriophyllum spicatum
63 : 200: Worms Euthamia
81 : 200: Worms Vicia cracca
98 : 200: Worms Elymus virginicus
89 : 200: Worms Erechtites hieraciifolius
101 : 200: Worms Cichorieae
102 : 200: Worms Eleocharis palustris

           Dataset Values  Validation Database values                        \
           ScientificName Exact_Match         TaxonID Status Unacceptreason
0    Phalaris arundinacea      Non/no
92  Lysimachia terrestris      Non/no
91           Spiraea alba      Non/no


   Taxon_Rank Valid_TaxonID Valid_Name LSID
0
92
91

In [12]:
table4.head(3)

                                  Ref. ID                Validation  \
                             OccurrenceID ScientificName_Validation
0  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-001                    Non/no
1  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-002                    Non/no
2  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-003                    Non/no

                                                             Dataset Values  \
  TaxonRank_Validation scientificNameID_Validation           ScientificName
0               Non/No                      Non/No     Phalaris arundinacea
1               Non/No                      Non/No  Sporobolus michauxianus
2               Non/No                      Non/No   Schoenoplectus pungens

                                                Database values             \
  TaxonRank                    ScientificNameID      Valid_Name Taxon_Rank
0   Species    urn:lsid:itis.gov:itis_tsn:41335
1   Species  urn:lsid:ipni.org:names:77145291-1
2   Species   urn:lsid:itis.gov:itis_tsn:508146


  LSID
0
1
2

Try the check_scientificname_and_ids function - itis_usage:

In [13]:
check_scientificname_and_ids(occurrence_core, 'names', itis_usage= True).head()

28 : 204: Worms Spiraea alba
2 : 204: Worms Lysimachia maritima
14 : 204: Worms Acorus americanus
0 : 200: Worms Carex
11 : 204: Worms Convallaria majalis
34 : 200: Worms Ulva intestinalis
29 : 200: Worms Osmunda claytoniana
39 : 204: Worms Iris versicolor
36 : 204: Worms Persicaria maculosa
35 : 200: Worms Tanacetum
46 : 204: Worms Epalpus signifer
24 : 200: Worms Plantago
47 : 200: Worms Stuckenia pectinata
21 : 204: Worms Berberis thunbergii
25 : 204: Worms Fraxinus
26 : 204: Worms Scutellaria galericulata
49 : 204: Worms Sium suave
19 : 204: Worms Chelone glabra
1 : 200: Worms Lonicera
13 : 200: Worms Ruppia maritima
15 : 204: Worms Phalaris arundinacea
7 : 204: Worms Argentina anserina
44 : 204: Worms Alisma triviale
6 : 200: Worms Rumex
57 : 204: Worms Thalictrum pubescens
16 : 200: Worms Tussilago farfara
10 : 204: Worms Myrica gale
5 : 200: Worms Eutrochium maculatum
22 : 200: Worms Rosaceae
9 : 200: Worms Agrostis gigantea
8 : 200: Worms Cirsium arvense
23 : 200: Worms Poaceae
17 : 204: Worms Oxybasis rubra
18 : 204: Worms Athyrium angustum
12 : 200: Worms Osmunda spectabilis
3 : 200: Worms Asteraceae
4 : 200: Worms Senecio
38 : 200: Worms Persicaria
50 : 204: Worms Hypericum perforatum
55 : 200: Worms Megaceryle alcyon
27 : 200: Worms Galium
48 : 200: Worms Ranunculus repens
20 : 200: Worms Jacobaea vulgaris
30 : 204: Worms Cornus rugosa
31 : 200: Worms Castor canadensis
32 : 204: Worms Schoenoplectus pungens
60 : 200: Worms Nuphar
40 : 204: Worms Amphicarpaea bracteata
42 : 200: Worms Cichorium intybus
45 : 204: Worms Lysimachia terrestris
86 : 204: Worms Lycopus uniflorus
123 : 204: Worms Crataegus
93 : 200: Worms Bryophyta
143 : 200: Worms Schoenoplectus
109 : 204: Worms Quercus rubra
58 : 204: Worms Stellaria graminea
51 : 204: Worms Halerpestes cymbalaria
136 : 204: Worms Mentha canadensis
33 : 200: Worms Leucanthemum vulgare
115 : 204: Worms Frangula alnus
133 : 200: Worms Oenothera
56 : 200: Worms Calidris minutilla
121 : 200: Worms Galium mollugo
53 : 204: Worms Euphorbia maculata
117 : 204: Worms Carex pallescens
110 : 204: Worms Sporobolus michauxianus
119 : 204: Worms Fraxinus pennsylvanica
78 : 200: Worms Sagittaria latifolia
98 : 200: Worms Elymus virginicus
126 : 204: Worms Betula papyrifera
41 : 200: Worms Glyceria
43 : 200: Worms Sonchus arvensis
124 : 204: Worms Rhagonycha fulva
132 : 200: Worms Scirpus
108 : 200: Worms Cyperaceae
118 : 200: Worms Onoclea sensibilis
138 : 200: Worms Larus argentatus
92 : 204: Worms Harmonia axyridis
96 : 204: Worms Sorbus
65 : 200: Worms Tracheophyta
91 : 200: Worms Doellingeria umbellata
79 : 204: Worms Linaria vulgaris
84 : 200: Worms Senecio viscosus
112 : 204: Worms Scutellaria lateriflora
141 : 204: Worms Thelypteris palustris
71 : 200: Worms Centaurea jacea
106 : 204: Worms Calystegia sepium
37 : 204: Worms Alnus incana
52 : 200: Worms Plantago major
137 : 200: Worms Lythrum salicaria
113 : 200: Worms Polistes fuscatus
66 : 204: Worms Alnus alnobetula
76 : 200: Worms Juncus
69 : 204: Worms Pastinaca sativa
99 : 204: Worms Apocynum cannabinum
63 : 200: Worms Euthamia
130 : 204: Worms Solanum dulcamara
122 : 204: Worms Viburnum opulus
94 : 200: Worms Myriophyllum spicatum
61 : 204: Worms Reynoutria japonica
131 : 200: Worms Cirsium
77 : 200: Worms Anthoxanthum odoratum
62 : 204: Worms Iris hookeri
139 : 204: Worms Scirpus microcarpus
101 : 200: Worms Cichorieae
54 : 204: Worms Hylotelephium telephium
140 : 200: Worms Thuja occidentalis
67 : 200: Worms Schoenoplectus tabernaemontani
105 : 204: Worms Arisaema triphyllum
73 : 204: Worms Cornus sericea
120 : 200: Worms Centaurea nigra
128 : 200: Worms Vicia
135 : 200: Worms Tanacetum vulgare
89 : 200: Worms Erechtites hieraciifolius
74 : 200: Worms Zizania
87 : 200: Worms Eleocharis uniglumis
100 : 204: Worms Stachys palustris
90 : 200: Worms Liliopsida
68 : 204: Worms Hypericum mutilum
0 : 200: Itis Phalaris arundinacea
1 : 200: Itis Sporobolus michauxianus - Empty answer
2 : 200: Itis Schoenoplectus pungens
3 : 200: Itis Oxybasis rubra - Empty answer
5 : 200: Itis Linaria vulgaris
11 : 200: Itis Halerpestes cymbalaria
13 : 200: Itis Chelone glabra
14 : 200: Itis Reynoutria japonica
20 : 200: Itis Arisaema triphyllum
23 : 200: Itis Stachys palustris
24 : 200: Itis Fraxinus pennsylvanica
25 : 200: Itis Sium suave
26 : 200: Itis Amphicarpaea bracteata
28 : 200: Itis Berberis thunbergii
29 : 200: Itis Mentha canadensis
30 : 200: Itis Carex pallescens
31 : 200: Itis Athyrium angustum
33 : 200: Itis Alnus incana
34 : 200: Itis Myrica gale
39 : 200: Itis Argentina anserina
40 : 200: Itis Crataegus
46 : 200: Itis Convallaria majalis
49 : 200: Itis Alnus alnobetula
51 : 200: Itis Iris hookeri
53 : 200: Itis Persicaria maculosa
56 : 200: Itis Calystegia sepium
58 : 200: Itis Euphorbia maculata
59 : 200: Itis Thelypteris palustris
60 : 200: Itis Thalictrum pubescens
63 : 200: Itis Hylotelephium telephium
66 : 200: Itis Epalpus signifer
67 : 200: Itis Rhagonycha fulva
70 : 200: Itis Hypericum perforatum
71 : 200: Itis Stellaria graminea
75 : 200: Itis Lysimachia maritima
78 : 200: Itis Harmonia axyridis
80 : 200: Itis Acorus americanus
81 : 200: Itis Scirpus microcarpus
82 : 200: Itis Solanum dulcamara
84 : 200: Itis Scutellaria lateriflora
85 : 200: Itis Frangula alnus
89 : 200: Itis Apocynum cannabinum
91 : 200: Itis Spiraea alba
92 : 200: Itis Lysimachia terrestris
93 : 200: Itis Lycopus uniflorus
98 : 200: Itis Scutellaria galericulata
99 : 200: Itis Betula papyrifera
110 : 200: Itis Cornus sericea
112 : 200: Itis Cornus rugosa
114 : 200: Itis Pastinaca sativa
115 : 200: Itis Alisma triviale
116 : 200: Itis Sorbus
124 : 200: Itis Fraxinus
126 : 200: Itis Viburnum opulus
132 : 200: Itis Iris versicolor
137 : 200: Itis Hypericum mutilum
142 : 200: Itis Quercus rubra

            Dataset Values  Validation Database values                        \
            scientificname Exact_Match         TaxonID Status Unacceptreason
127            Acer rubrum      Non/no
105         Symphyotrichum      Non/no
52   Raphanus raphanistrum      Non/no
108    Persicaria amphibia      Non/no
79     Echinocystis lobata      Non/no


    Taxon_Rank Valid_TaxonID Valid_Name LSID
127
105
52
108
79